apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fx96qd264-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-4d6a9ad65b.e25m.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:ef5f4a959a9f8e5c9ca4f7fadf94382b5be89b60@sha256:fe6e0ae170fe7fdc5a03d57df14409901e88b4061f6e88a7deeb408cf5b5265b
          name: container-image
